### ISSUE TITLE
Create better test data for dummy DAOs

### ISSUE THREAD

**Issue by chilloutman** [chilloutman/photo-flow#1]
Damit GUI-Entwicklung bereits ein DAO verwenden kann, sollten einige Dummy-Bilder und Dummy-Projekte entstehen.

Vorher müssen die Domain-Klassen alle Attribute haben.

**Comment by chilloutman** [comment]
done.

**Comment by chilloutman** [comment]
@joshfreak7

**Comment by joshfreak7** [comment]
So läss

**Comment by DeeVeX** [comment]
ischs jetzt done oder nöd? :P

**Comment by chilloutman** [comment]
Nöd done. Müsst me no es paar Demo-Bilder und so ha. Und es paar DAO-Methode sind nonig implementiert.

**Comment by chilloutman** [comment]
Dummy-Projekte sind drin. Dummy-Bilder fehlen noch gänzlich.
