### ISSUE TITLE
Konstruktoren in Domain- und DAO-Klassen erstellen

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#10]
- Übergabeparameter definieren
- Body befüllen

**Comment by chilloutman** [comment]
Done.

`Photo` und `Project` werden im `InMemory*Dao` immer kopiert, damit man die Änderungen nicht sofort  im Dao gespeichert sind. Das emuliert so die SQL-Daos, wo das immer so ist, dass man die DB mit dem verändern der Domain-Objekte nicht automatisch verändert wird. Zum speichern **muss** man `save()` aufrufen.

Kleine Domain-Klassen (Im Klassendiagram als Komposition) sind immutable (Es gibt keine Setter). Das hilft z.B. beim kopieren.
