### ISSUE TITLE
FileHandler implementieren

### ISSUE THREAD

**Issue by chilloutman** [chilloutman/photo-flow#16]
Klasse `FileHandler` gemäss Design-Dokument implementieren. Am besten gleich **mit Unit-Tests**.

**Comment by chilloutman** [comment]
Bitte die Pfade irgendwo dokumentieren. Vielleicht gleich in Google Docs eine "Benutzeranleitung" erstellen und dort die Pfade nur mal hinschreiben.

**Comment by chilloutman** [comment]
Am besten gleich mit Unit-Tests. (gleich fürs SWEN-Praktikum)

Eventuell die Tests ein Temp-Directory erstellen (siehe Java-File-API) und dann dort ein directories und files herumschieben. Das dürfte dann auch schon fast als Integration-Test durchgehen.

**Comment by joshfreak7** [comment]
Implementiert: Zip Export, loadFile, importPhoto und UnitTests.
