### ISSUE TITLE
Unit Tests für FileHandler

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#21]

**Comment by chilloutman** [comment]
Weshalb erst nach #16? Unit-Tests bringen am meisten, wenn man sie gleich während der Implementation macht.

**Comment by joshfreak7** [comment]
Hans efach genau glich wie all andere unit tests gmacht. ohni bestimmte grund. aber ish klar während machts am meishte sinn.

**Comment by chilloutman** [comment]
K. Alles klar.

**Comment by joshfreak7** [comment]
Tests erstellt und erfolgreich getestet.
