### ISSUE TITLE
UC002 - Fotos importieren

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#23]
- [x] 1. Button: "Import Photos"
- [x] 2. Explorer/Finder-Dialog geht auf
- [x] 3. Bilder werden in den Projekt-Ordner kopiert. (FileHandler)
- [x] 4. Thumbnails speichern (FileHandler)
- [x] 5. In PictureDao einfügen.

**Comment by joshfreak7** [comment]
Thumbnails? Muss das de FileHandler no mache?

**Comment by DeeVeX** [comment]
De Lucas cha d'grössi vode Bilder rächt agnähm ide ImageView agäh.
Dänn wirds zwar bi jedem Projektwechsel neu usgrächnet, aber Performancemässig langeds.

**Comment by chilloutman** [comment]
Fertig. Thumbnails werden einfach on-the-fly generiert.
