### ISSUE TITLE
UC005 - Metadaten Handling

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#26]
- [x] Metadaten in FileHandler laden
- [x] Interessante Metataden filter und für bessere Darstellung aufbereiten.
- [x] Metadaten in Photo-Detail-View anzeigen.

**Comment by chilloutman** [comment]
Darstellung ist nicht super, aber aus meiner Sicht OK. Einige Exif-Einträge werden gefiltert. Wenn es zu viele gibt, kann gescrollt werden.
