### ISSUE TITLE
UC006 - Fotos kategorisieren

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#27]
- [x] In `PhotoController`: Flag- und Discard-Button.
- [x] Discarded/Flagged in der Photo-Übersicht visualisieren.

**Comment by chilloutman** [comment]
Man könnte noch das CSS verbessern.

Um momentan macht der Border auch das Bild-Node ein bisschen grösser, was dazu führen kann, dass das die Photos etwas springen. Mache das Issue aber trotzdem zu.
