### ISSUE TITLE
Error Messages to GUI

### ISSUE THREAD

**Issue by joshfreak7** [chilloutman/photo-flow#36]
Exception Handling:
- [x] Dialog für Fehlermeldungen
- [ ] Calls einfügen
- [x] Technische Fehlermeldungen verständlich für User umformulieren

**Comment by chilloutman** [comment]
Wichtig: Exception nicht mehr einfach catchen und nichts machen.

Bis es den Dialog gibt: `throw new RuntimeException(e);` oder mindestens etwas in `System.out` ausgehen.

Ansonsten sieht man gar nicht, wenn etwas nicht funktioniert.

**Comment by SimonGadgeteer** [comment]
Done für die wichtigsten Meldungen
