### ISSUE TITLE
ProjectController: Button-Stati von den ProjectWorkflow-Regeln abhängig machen.

### ISSUE THREAD

**Issue by chilloutman** [chilloutman/photo-flow#40]
In `ProjectController.updateWorkflowButtons()` wird entschieden, welche Buttons enabled und welche disabled sind.

Diese Logik ist mit `ProjectWorkflow.canTransition` definiert und sollte im Controller nicht dupliziert werden.

**Comment by chilloutman** [comment]
@joshfreak7 Ich wis der mal zue, will du das gmacht häsch. Wenn öpis unklar isch, schrib mer. Wenn du a öpis wichtegerem bisch, chan ich das au mache.

**Comment by joshfreak7** [comment]
Done. Chliine funktionsufruef jedes mal wenn gflagt oder discarded wird fehlt no, ghört den aber zum Buglist-Issue.
