### ISSUE TITLE
Create Executable (Windows, OS X)

### ISSUE THREAD

**Issue by chilloutman** [chilloutman/photo-flow#42]
Aktuelles Problem: `java.nio.file.FileSystemNotFoundException: null` beim starten.

Momentan läuft die Applikation ohne eclipse gar nicht. Zumindest auf OS X.

**Comment by chilloutman** [comment]
`java.nio.file.FileSystemNotFoundException: null` gefixt.

**Comment by chilloutman** [comment]
`PhotoFlow.app` wird jetzt erstellt und funktioniert. JRE wird auch integriert.

`PhotoFlow.exe` stellt sich noch als schwierig heraus. `gardle-launch4j` funktioniert noch nicht. JRE bündeln scheint nicht ganz so einfach.

Alternativ kann man manuell mit Eclipse via `Export -> Runnable Jar File` wenigstens mal ein Jar-File erstellen.

**Comment by joshfreak7** [comment]
Die exe steht! Inklusive JRE.
